language: ruby

services:
  - mysql

rvm:
  - 1.9.3
  - 2.0.0

gemfile:
  - $REDMINE_PATH/Gemfile

env:
  - REDMINE_VER=2.1.6
  - REDMINE_VER=2.2.4
  - REDMINE_VER=2.3.3
  - REDMINE_VER=2.3.4
  - REDMINE_VER=2.4.7
  - REDMINE_VER=2.5.3
  - REDMINE_VER=2.6.0

matrix:
  exclude:
    - rvm: 2.0.0
      env: REDMINE_VER=2.1.6
      gemfile: $REDMINE_PATH/Gemfile
    - rvm: 2.0.0
      env: REDMINE_VER=2.2.4
      gemfile: $REDMINE_PATH/Gemfile

before_install:
  - export PLUGIN_NAME=redmine_repository_default_check
  - export DB=mysql
  - export REDMINE_PATH=$HOME/redmine
  - svn co http://svn.redmine.org/redmine/tags/$REDMINE_VER $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake redmine:plugins:migrate

script:
  - bundle exec rake redmine:plugins:test NAME=$PLUGIN_NAME
